// <auto-generated />
using System;
using FineArt.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FineArt.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20251117090742_AddCafeStyleBoards")]
    partial class AddCafeStyleBoards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FineArt.Domain.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Views")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BoardTypeId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_articles_created_at");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 90001,
                            BoardTypeId = 1,
                            Content = "FineArt 시스템 점검이 예정되어 있습니다. 점검 시간 동안 일부 서비스 이용이 제한될 수 있습니다.",
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@fineart.local",
                            Title = "서버 점검 안내",
                            UpdatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Views = 0,
                            Writer = "관리자"
                        },
                        new
                        {
                            Id = 90002,
                            BoardTypeId = 3,
                            Content = "2025 서울 아트페어에 참가할 작가를 모집합니다.",
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "news@fineart.local",
                            Title = "서울 아트페어 참가 공모",
                            UpdatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Views = 0,
                            Writer = "서울문화재단"
                        },
                        new
                        {
                            Id = 90003,
                            BoardTypeId = 5,
                            Content = "우하남 작가의 전시가 FineArt Cube에서 개최됩니다.",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "event@fineart.local",
                            Title = "우하남展 개최",
                            UpdatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Views = 0,
                            Writer = "FineArt"
                        });
                });

            modelBuilder.Entity("FineArt.Domain.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Bio = "빛과 도시를 주제로 한 뉴미디어 설치·회화 작가.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80",
                            Name = "미나 허",
                            Nationality = "대한민국"
                        },
                        new
                        {
                            Id = 1002,
                            Bio = "물성과 색채 실험을 지속하는 2인 페인팅 그룹.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1475688621402-4257f5b911ef?auto=format&fit=crop&w=800&q=80",
                            Name = "라텍스 듀오",
                            Nationality = "대한민국"
                        },
                        new
                        {
                            Id = 1003,
                            Bio = "공간과 공감을 탐구하는 혼합재료 작가.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=800&q=80",
                            Name = "이수현",
                            Nationality = "대한민국"
                        },
                        new
                        {
                            Id = 1004,
                            Bio = "도시 속 자연을 포착하는 수채 기반 작가.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=800&q=80",
                            Name = "서현 리",
                            Nationality = "대한민국"
                        },
                        new
                        {
                            Id = 1005,
                            Bio = "사운드와 색을 결합한 추상 회화 실험자.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1462219184705-54ee45569803?auto=format&fit=crop&w=800&q=80",
                            Name = "이안 최",
                            Nationality = "대한민국"
                        },
                        new
                        {
                            Id = 1006,
                            Bio = "식물성과 감각을 섬세한 레이어로 확장한다.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
                            Name = "윤세라",
                            Nationality = "대한민국"
                        },
                        new
                        {
                            Id = 1007,
                            Bio = "도시 풍경을 시네마틱 색감으로 재해석.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=801&q=80",
                            Name = "루시 박",
                            Nationality = "대한민국"
                        },
                        new
                        {
                            Id = 1008,
                            Bio = "차분한 색면으로 빛의 변주를 연주하는 작가.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=800&q=80",
                            Name = "김이노",
                            Nationality = "대한민국"
                        },
                        new
                        {
                            Id = 1009,
                            Bio = "우주적 상상력을 그래픽 라인으로 기록.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=801&q=80",
                            Name = "에바 장",
                            Nationality = "대한민국"
                        },
                        new
                        {
                            Id = 1010,
                            Bio = "대형 캔버스에서 조명과 음향을 회화화한다.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=802&q=80",
                            Name = "박유성",
                            Nationality = "대한민국"
                        });
                });

            modelBuilder.Entity("FineArt.Domain.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtistDisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Artist");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsRentable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("MainTheme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("RentPrice")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubTheme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_artwork_created_at");

                    b.HasIndex("MainTheme")
                        .HasDatabaseName("idx_artwork_theme");

                    b.HasIndex("Price")
                        .HasDatabaseName("idx_artwork_price");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_artwork_status");

                    b.ToTable("Artworks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistDisplayName = "미나 허",
                            ArtistId = 1001,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "서울의 야경을 아크릴 레이어로 재해석한 시티 캔버스.",
                            ImageUrl = "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1200&q=80",
                            IsRentable = true,
                            MainTheme = "풍경",
                            Material = "아크릴",
                            Price = 2900000,
                            RentPrice = 480000,
                            Size = "91x117cm · 80호 이상",
                            Status = 2,
                            SubTheme = "도시 조명",
                            Title = "Seoul Lightscape",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ArtistDisplayName = "라텍스 듀오",
                            ArtistId = 1002,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "광물성 안료가 겹겹이 쌓여 만들어낸 열감 있는 추상 회화.",
                            ImageUrl = "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=1200&q=80",
                            IsRentable = false,
                            MainTheme = "추상",
                            Material = "유화",
                            Price = 1800000,
                            Size = "73x91cm · 30호~50호",
                            Status = 0,
                            SubTheme = "감각",
                            Title = "Warm Mineral",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ArtistDisplayName = "이수현",
                            ArtistId = 1003,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "잉크와 혼합재료로 공간감과 몰입을 강조한 시리즈.",
                            ImageUrl = "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
                            IsRentable = false,
                            MainTheme = "상상",
                            Material = "혼합재료",
                            Price = 4200000,
                            Size = "100x100cm · 50호~80호",
                            Status = 0,
                            SubTheme = "미래 공간",
                            Title = "Void Ink - Capsule",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ArtistDisplayName = "서현 리",
                            ArtistId = 1004,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "새벽빛을 머금은 작은 화병의 따스한 색감을 수채층으로 담았다.",
                            ImageUrl = "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1000&q=80",
                            IsRentable = true,
                            MainTheme = "정물",
                            Material = "수채",
                            Price = 620000,
                            RentPrice = 150000,
                            Size = "45x53cm · 15호",
                            Status = 2,
                            SubTheme = "플로럴",
                            Title = "Amber Bloom",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            ArtistDisplayName = "이안 최",
                            ArtistId = 1005,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "전자음과 파도 소리를 시각화한 네온 스트로크.",
                            ImageUrl = "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
                            IsRentable = false,
                            MainTheme = "상상",
                            Material = "혼합재료",
                            Price = 2800000,
                            Size = "120x80cm · 60호",
                            Status = 0,
                            SubTheme = "사운드 파동",
                            Title = "Midnight Current",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            ArtistDisplayName = "윤세라",
                            ArtistId = 1006,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "유리 온실 속 증기를 연두빛 레이어로 번지게 했다.",
                            ImageUrl = "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80",
                            IsRentable = true,
                            MainTheme = "정물",
                            Material = "아크릴",
                            Price = 1250000,
                            RentPrice = 320000,
                            Size = "80x60cm · 25호",
                            Status = 2,
                            SubTheme = "보타닉",
                            Title = "Botanic Whisper",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            ArtistDisplayName = "미나 허",
                            ArtistId = 1001,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "레이저 빛의 간격으로 만들어낸 지평선의 박동.",
                            ImageUrl = "https://images.unsplash.com/photo-1500534312200-a16b66c0f3b9?auto=format&fit=crop&w=1200&q=80",
                            IsRentable = false,
                            MainTheme = "풍경",
                            Material = "아크릴",
                            Price = 3400000,
                            Size = "100x60cm · 40호",
                            Status = 0,
                            SubTheme = "지평선",
                            Title = "Horizon Pulse",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            ArtistDisplayName = "이안 최",
                            ArtistId = 1005,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "대양의 층위를 곡선 스트로크로 덧칠한 추상 회고록.",
                            ImageUrl = "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=81",
                            IsRentable = false,
                            MainTheme = "추상",
                            Material = "유화",
                            Price = 2050000,
                            Size = "91x91cm · 50호",
                            Status = 1,
                            SubTheme = "해양",
                            Title = "Cerulean Memoir",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            ArtistDisplayName = "루시 박",
                            ArtistId = 1007,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "해질녘 골목의 분홍빛 공기를 영화 스틸컷처럼 구현했다.",
                            ImageUrl = "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=81",
                            IsRentable = true,
                            MainTheme = "풍경",
                            Material = "아크릴",
                            Price = 1450000,
                            RentPrice = 360000,
                            Size = "73x91cm · 30호~50호",
                            Status = 2,
                            SubTheme = "도시 산책",
                            Title = "Dusty Pink Alley",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            ArtistDisplayName = "김이노",
                            ArtistId = 1008,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "밤 설원을 미드나잇 블루와 차콜 그라데이션으로 표현.",
                            ImageUrl = "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1100&q=80",
                            IsRentable = false,
                            MainTheme = "풍경",
                            Material = "유화",
                            Price = 3900000,
                            Size = "130x97cm · 80호 이상",
                            Status = 0,
                            SubTheme = "설경",
                            Title = "Northern Quiet",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            ArtistDisplayName = "이수현",
                            ArtistId = 1003,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "수중 생명체를 유리조각처럼 절제된 라인으로 묘사.",
                            ImageUrl = "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1100&q=80",
                            IsRentable = true,
                            MainTheme = "동물",
                            Material = "혼합재료",
                            Price = 1980000,
                            RentPrice = 420000,
                            Size = "88x60cm · 25호",
                            Status = 2,
                            SubTheme = "수중",
                            Title = "Glass Reef",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            ArtistDisplayName = "에바 장",
                            ArtistId = 1009,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "궤도를 따라 움직이는 점과 선의 모션을 모노라인으로 기록.",
                            ImageUrl = "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1000&q=80",
                            IsRentable = true,
                            MainTheme = "상상",
                            Material = "드로잉",
                            Price = 780000,
                            RentPrice = 190000,
                            Size = "60x60cm · 20호",
                            Status = 2,
                            SubTheme = "우주",
                            Title = "Orbit Sketch",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            ArtistDisplayName = "윤세라",
                            ArtistId = 1006,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "깊은 녹색과 자주색을 벨벳처럼 번지게 한 정물 연작.",
                            ImageUrl = "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80",
                            IsRentable = false,
                            MainTheme = "정물",
                            Material = "오일파스텔",
                            Price = 1120000,
                            Size = "92x60cm · 30호",
                            Status = 1,
                            SubTheme = "텍스타일",
                            Title = "Velvet Stillness",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            ArtistDisplayName = "박유성",
                            ArtistId = 1010,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "공연장의 조명과 음향 파형을 다층 레이어로 시각화.",
                            ImageUrl = "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=1300&q=80",
                            IsRentable = true,
                            MainTheme = "추상",
                            Material = "아크릴",
                            Price = 5400000,
                            RentPrice = 720000,
                            Size = "162x112cm · 120호",
                            Status = 2,
                            SubTheme = "공연장",
                            Title = "Luminous Stage",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            ArtistDisplayName = "서현 리",
                            ArtistId = 1004,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "햇살을 받아 분해되는 프리즘 정원을 색면으로 나눴다.",
                            ImageUrl = "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1150&q=80",
                            IsRentable = false,
                            MainTheme = "정물",
                            Material = "수채",
                            Price = 1650000,
                            Size = "80x100cm · 50호",
                            Status = 0,
                            SubTheme = "정원",
                            Title = "Prism Garden",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            ArtistDisplayName = "김이노",
                            ArtistId = 1008,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "라디오 노이즈와 새벽빛의 색조를 결합한 색면 회화.",
                            ImageUrl = "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1180&q=80",
                            IsRentable = true,
                            MainTheme = "추상",
                            Material = "유화",
                            Price = 2600000,
                            RentPrice = 500000,
                            Size = "116x89cm · 60호",
                            Status = 0,
                            SubTheme = "새벽",
                            Title = "Analog Dawn",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FineArt.Domain.BoardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit(1)");

                    b.Property<int>("LayoutType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BoardTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "사이트 및 전시 관련 공지",
                            IsVisible = true,
                            LayoutType = 0,
                            Name = "공지사항",
                            OrderIndex = 0,
                            Slug = "notice",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "사용자 자유 토론",
                            IsVisible = true,
                            LayoutType = 0,
                            Name = "자유게시판",
                            OrderIndex = 0,
                            Slug = "free",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "예술 관련 뉴스",
                            IsVisible = true,
                            LayoutType = 0,
                            Name = "뉴스",
                            OrderIndex = 0,
                            Slug = "news",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "미술 관련 채용 공고",
                            IsVisible = true,
                            LayoutType = 0,
                            Name = "채용",
                            OrderIndex = 0,
                            Slug = "recruit",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "FineArt 주관 행사 소식",
                            IsVisible = true,
                            LayoutType = 0,
                            Name = "전시/행사",
                            OrderIndex = 0,
                            Slug = "exhibition",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FineArt.Domain.Exhibition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("Group");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_exhibitions_category");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("idx_exhibitions_schedule");

                    b.ToTable("Exhibitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "이수현",
                            Category = "Digital",
                            CreatedAt = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "디지털 확장 설치전. FineArt Cube 전체를 감싸는 몰입형 잉크 라이트 설치입니다.",
                            EndDate = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Cube",
                            StartDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Void Ink · 여백의 잔상"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "미나 허",
                            Category = "Group",
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "미디어 회화전. OLED 페인트 패널과 투명 스크린으로 서울의 야경을 재해석합니다.",
                            EndDate = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Cube",
                            StartDate = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Seoul Lightscape"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "라텍스 듀오",
                            Category = "Installation",
                            CreatedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "조명 작업전. 섬세한 석고 텍스처와 광섬유를 결합한 라텍스 듀오의 신작.",
                            EndDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1465311440653-ba9b1d68da21?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Gallery",
                            StartDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Warm Mineral"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "서이현",
                            Category = "Solo",
                            CreatedAt = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "은은한 빛으로 숨 쉬는 인터랙티브 식물 설치. 관람자의 움직임에 따라 잎맥이 발광합니다.",
                            EndDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Green Room",
                            StartDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Luminary Garden"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Collective Prism",
                            Category = "Group",
                            CreatedAt = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "수평선처럼 펼쳐지는 색면 미디어. 8K 레이어가 시간에 따라 서서히 이동합니다.",
                            EndDate = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Cube",
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Chromatic Drift"
                        },
                        new
                        {
                            Id = 6,
                            Artist = "이마루 & 윤채",
                            Category = "Group",
                            CreatedAt = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "도자기 조각 위에 프로젝션 맵핑을 입혀 소리와 색이 울리는 설치전.",
                            EndDate = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Atelier",
                            StartDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Echoes of Clay"
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Studio Nabile",
                            Category = "Digital",
                            CreatedAt = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "공간 전체를 사용하는 270도 홀로그램 연출과 클래식 사운드의 만남.",
                            EndDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1482192505345-5655af888cc4?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Dome",
                            StartDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Hologram Opera"
                        },
                        new
                        {
                            Id = 8,
                            Artist = "린다 베르그",
                            Category = "Solo",
                            CreatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "극지방의 빛을 기록한 사진과 사운드 아카이브를 immersive 환경으로 재현.",
                            EndDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Vault",
                            StartDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Northbound Light"
                        },
                        new
                        {
                            Id = 9,
                            Artist = "Paper Assembly",
                            Category = "Installation",
                            CreatedAt = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "거대한 종이 구조물을 쌓아 도시 풍경을 재구성하는 설치 프로젝트.",
                            EndDate = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Warehouse",
                            StartDate = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Paper Tectonics"
                        },
                        new
                        {
                            Id = 10,
                            Artist = "Co.studio Bloom",
                            Category = "Installation",
                            CreatedAt = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "향과 빛, 사운드를 결합해 계절의 변화를 체험하게 하는 몰입형 정원.",
                            EndDate = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Pavilion",
                            StartDate = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sensorial Bloom"
                        },
                        new
                        {
                            Id = 11,
                            Artist = "장도현",
                            Category = "Digital",
                            CreatedAt = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "레이저 스캔으로 기록한 도시의 잔상을 데이터 조각으로 시각화.",
                            EndDate = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Research Lab",
                            StartDate = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Afterimage Waves"
                        },
                        new
                        {
                            Id = 12,
                            Artist = "FineArt Robot Lab",
                            Category = "Group",
                            CreatedAt = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "수장고에서 꺼낸 모듈 조각을 로봇 암으로 재배열하는 라이브 퍼포먼스.",
                            EndDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1475688621402-4257a8543cfe?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Machine Room",
                            StartDate = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Kinetic Archive"
                        },
                        new
                        {
                            Id = 13,
                            Artist = "Atmos Lab",
                            Category = "Installation",
                            CreatedAt = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "안개를 분사하는 대형 지도 구조와 프로젝션을 결합해 도시 기후를 표현.",
                            EndDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Plaza",
                            StartDate = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Mist City Atlas"
                        },
                        new
                        {
                            Id = 14,
                            Artist = "Mira Collective",
                            Category = "Digital",
                            CreatedAt = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "수중 녹음을 재구성한 사운드 인스톨레이션과 빛의 파동 퍼포먼스.",
                            EndDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1475694867812-f82b8696d610?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Hall B1",
                            StartDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Aquifer Chorus"
                        });
                });

            modelBuilder.Entity("FineArt.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FineArt.Domain.Article", b =>
                {
                    b.HasOne("FineArt.Domain.BoardType", "BoardType")
                        .WithMany("Articles")
                        .HasForeignKey("BoardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardType");
                });

            modelBuilder.Entity("FineArt.Domain.Artwork", b =>
                {
                    b.HasOne("FineArt.Domain.Artist", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("FineArt.Domain.Artist", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("FineArt.Domain.BoardType", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
