// <auto-generated />
using System;
using FineArt.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FineArt.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20251111065719_InitAppDb")]
    partial class InitAppDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FineArt.Domain.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Views")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_articles_category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_articles_created_at");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("FineArt.Domain.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Bio = "빛과 도시를 주제로 한 뉴미디어 설치·회화 작가.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80",
                            Name = "미나 허",
                            Nationality = "대한민국"
                        },
                        new
                        {
                            Id = 1002,
                            Bio = "물성과 색채 실험을 지속하는 2인 페인팅 그룹.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1475688621402-4257f5b911ef?auto=format&fit=crop&w=800&q=80",
                            Name = "라텍스 듀오",
                            Nationality = "대한민국"
                        },
                        new
                        {
                            Id = 1003,
                            Bio = "공간과 공감을 탐구하는 혼합재료 작가.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=800&q=80",
                            Name = "이수현",
                            Nationality = "대한민국"
                        });
                });

            modelBuilder.Entity("FineArt.Domain.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtistDisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Artist");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsRentable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("MainTheme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("RentPrice")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubTheme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_artwork_created_at");

                    b.HasIndex("MainTheme")
                        .HasDatabaseName("idx_artwork_theme");

                    b.HasIndex("Price")
                        .HasDatabaseName("idx_artwork_price");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_artwork_status");

                    b.ToTable("Artworks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistDisplayName = "미나 허",
                            ArtistId = 1001,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "서울의 야경을 아크릴 레이어로 재해석한 시티 캔버스.",
                            ImageUrl = "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1200&q=80",
                            IsRentable = true,
                            MainTheme = "풍경",
                            Material = "아크릴",
                            Price = 2900000,
                            RentPrice = 480000,
                            Size = "91x117cm · 80호 이상",
                            Status = 2,
                            SubTheme = "도시 조명",
                            Title = "Seoul Lightscape",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ArtistDisplayName = "라텍스 듀오",
                            ArtistId = 1002,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "광물성 안료가 겹겹이 쌓여 만들어낸 열감 있는 추상 회화.",
                            ImageUrl = "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=1200&q=80",
                            IsRentable = false,
                            MainTheme = "추상",
                            Material = "유화",
                            Price = 1800000,
                            Size = "73x91cm · 30호~50호",
                            Status = 0,
                            SubTheme = "감각",
                            Title = "Warm Mineral",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ArtistDisplayName = "이수현",
                            ArtistId = 1003,
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "잉크와 혼합재료로 공간감과 몰입을 강조한 시리즈.",
                            ImageUrl = "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
                            IsRentable = false,
                            MainTheme = "상상",
                            Material = "혼합재료",
                            Price = 4200000,
                            Size = "100x100cm · 50호~80호",
                            Status = 0,
                            SubTheme = "미래 공간",
                            Title = "Void Ink - Capsule",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FineArt.Domain.Exhibition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("Group");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_exhibitions_category");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("idx_exhibitions_schedule");

                    b.ToTable("Exhibitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "이수현",
                            Category = "Digital",
                            CreatedAt = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "디지털 확장 설치전. FineArt Cube 전체를 감싸는 몰입형 잉크 라이트 설치입니다.",
                            EndDate = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Cube",
                            StartDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Void Ink · 여백의 잔상"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "미나 허",
                            Category = "Group",
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "미디어 회화전. OLED 페인트 패널과 투명 스크린으로 서울의 야경을 재해석합니다.",
                            EndDate = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Cube",
                            StartDate = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Seoul Lightscape"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "라텍스 듀오",
                            Category = "Installation",
                            CreatedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "조명 작업전. 섬세한 석고 텍스처와 광섬유를 결합한 라텍스 듀오의 신작.",
                            EndDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1465311440653-ba9b1d68da21?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Gallery",
                            StartDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Warm Mineral"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "서이현",
                            Category = "Solo",
                            CreatedAt = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "은은한 빛으로 숨 쉬는 인터랙티브 식물 설치. 관람자의 움직임에 따라 잎맥이 발광합니다.",
                            EndDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Green Room",
                            StartDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Luminary Garden"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Collective Prism",
                            Category = "Group",
                            CreatedAt = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "수평선처럼 펼쳐지는 색면 미디어. 8K 레이어가 시간에 따라 서서히 이동합니다.",
                            EndDate = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Cube",
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Chromatic Drift"
                        },
                        new
                        {
                            Id = 6,
                            Artist = "이마루 & 윤채",
                            Category = "Group",
                            CreatedAt = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "도자기 조각 위에 프로젝션 맵핑을 입혀 소리와 색이 울리는 설치전.",
                            EndDate = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Atelier",
                            StartDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Echoes of Clay"
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Studio Nabile",
                            Category = "Digital",
                            CreatedAt = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "공간 전체를 사용하는 270도 홀로그램 연출과 클래식 사운드의 만남.",
                            EndDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1482192505345-5655af888cc4?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Dome",
                            StartDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Hologram Opera"
                        },
                        new
                        {
                            Id = 8,
                            Artist = "린다 베르그",
                            Category = "Solo",
                            CreatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "극지방의 빛을 기록한 사진과 사운드 아카이브를 immersive 환경으로 재현.",
                            EndDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Vault",
                            StartDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Northbound Light"
                        },
                        new
                        {
                            Id = 9,
                            Artist = "Paper Assembly",
                            Category = "Installation",
                            CreatedAt = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "거대한 종이 구조물을 쌓아 도시 풍경을 재구성하는 설치 프로젝트.",
                            EndDate = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Warehouse",
                            StartDate = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Paper Tectonics"
                        },
                        new
                        {
                            Id = 10,
                            Artist = "Co.studio Bloom",
                            Category = "Installation",
                            CreatedAt = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "향과 빛, 사운드를 결합해 계절의 변화를 체험하게 하는 몰입형 정원.",
                            EndDate = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Pavilion",
                            StartDate = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sensorial Bloom"
                        },
                        new
                        {
                            Id = 11,
                            Artist = "장도현",
                            Category = "Digital",
                            CreatedAt = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "레이저 스캔으로 기록한 도시의 잔상을 데이터 조각으로 시각화.",
                            EndDate = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Research Lab",
                            StartDate = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Afterimage Waves"
                        },
                        new
                        {
                            Id = 12,
                            Artist = "FineArt Robot Lab",
                            Category = "Group",
                            CreatedAt = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "수장고에서 꺼낸 모듈 조각을 로봇 암으로 재배열하는 라이브 퍼포먼스.",
                            EndDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1475688621402-4257a8543cfe?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Machine Room",
                            StartDate = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Kinetic Archive"
                        },
                        new
                        {
                            Id = 13,
                            Artist = "Atmos Lab",
                            Category = "Installation",
                            CreatedAt = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "안개를 분사하는 대형 지도 구조와 프로젝션을 결합해 도시 기후를 표현.",
                            EndDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Plaza",
                            StartDate = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Mist City Atlas"
                        },
                        new
                        {
                            Id = 14,
                            Artist = "Mira Collective",
                            Category = "Digital",
                            CreatedAt = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "수중 녹음을 재구성한 사운드 인스톨레이션과 빛의 파동 퍼포먼스.",
                            EndDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1475694867812-f82b8696d610?auto=format&fit=crop&w=2000&q=80",
                            Location = "FineArt Hall B1",
                            StartDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Aquifer Chorus"
                        });
                });

            modelBuilder.Entity("FineArt.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FineArt.Domain.Artwork", b =>
                {
                    b.HasOne("FineArt.Domain.Artist", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("FineArt.Domain.Artist", b =>
                {
                    b.Navigation("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
